name: Deploy config to DB

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current develop
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
            python-version: '3.9.13'
      - name: Setup Python
        run: python -m pip install --upgrade pip requests jsondiff
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Execute script
        env:
          API_USER: ${{secrets.DEV_USERNAME}}
          API_PASSWORD: ${{secrets.DEV_PASSWORD}}
        run: |
         python scripts/test.py
